### ISSUE TITLE
Feature: the ability to start with docker port

### ISSUE THREAD

**Issue by iam-dev** [PureStake/moonbeam-truffle-plugin#1]
Something like:
truffle run moonbeam start --p 7545

Issue:
Right now docker run doenst open up any port using truffle run moonbeam start

**Comment by albertov19** [comment]
Just saw this, sorry if it is too late. We will work on adding this said feature.

**Comment by joelamouche** [comment]
@albertov19 @eshaben So can we close this issue?

**Comment by eshaben** [comment]
yes! closing it... thanks @joelamouche
