### ISSUE TITLE
Not able to install moonbeam-truffle-plugin

### ISSUE THREAD

**Issue by newbie101gen** [PureStake/moonbeam-truffle-plugin#4]
I was following the instructions on the official documentation and execute the following command:

`` truffle run moonbeam install``

And got following error message:

``Error: 
Error: moonbeam-truffle-plugin listed as a plugin, but not found in global or local node modules!``

Is anyone else having the same issue?

**Comment by joelamouche** [comment]
Hi @ai323 ,
I was not able to reproduce... Can you try rebuilding the moonbeam truffle box from scratch? Did you follow the instructions here : https://github.com/PureStake/moonbeam-truffle-box ?

**Comment by newbie101gen** [comment]
> Hi @ai323 ,
> I was not able to reproduce... Can you try rebuilding the moonbeam truffle box from scratch? Did you follow the instructions here : https://github.com/PureStake/moonbeam-truffle-box ?

Hey, I resolved the issue by adding `~/.npm-global/bin/` to my `$PATH`

**Comment by joelamouche** [comment]
Ok great :)
